# Build and publish qto-ui with npm + Gradle

name: Gradle Package

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qto-ui
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up Java for Gradle
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - run: npm ci
      - run: npm run build --omit=dev
      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Create zip
        run: |
          cd dist/qto-ui
          zip -r qto-ui-${{steps.package-version.outputs.current-version}}-SNAPSHOT.zip .
      - name: Publish to GitHub Packages with Gradle
        run: ../qto/gradlew -p . publishGprPublicationToGitHubPackagesRepository -PpublishVersion=${{steps.package-version.outputs.current-version}}-SNAPSHOT
        env:
          GITHUB_ACTOR: mwelicka
          GITHUB_TOKEN: ${{ secrets.RC_PACKAGES_READ_WRITE_TOKEN }}
