name: 'CI on pull request'

on:
  workflow_dispatch:

# cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max-old-space-size=8192

jobs:
  ##################
  # install dependencies
  setup_deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qto-ui
    steps:
      - name: No label
        if: ${{ github.event.label.name != 'Activate CI' }}
        run: |
          curl \
          -X DELETE \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: token ${{ github.token }}' \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/Activate%20CI
          echo "Run failed because 'Activate CI' label was not set. Add the label to the PR to retry run."
          exit 1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        id: cache
        with:
          path: qto-ui/node_modules
          key: qto_node_modules-${{ hashFiles('qto-ui/bun.lock') }}
      - name: Remove test label
        run: |
          curl \
          -X DELETE \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: token ${{ github.token }}' \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/Activate%20CI
      - uses: oven-sh/setup-bun@v2
      - name: Bun Install
        run: bun install

  # unit tests
  test:
    name: Test
    needs: setup_deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: qto-ui/node_modules
          key: qto_node_modules-${{ hashFiles('qto-ui/bun.lock') }}
      - uses: oven-sh/setup-bun@v2
      - name: CI Test
        run: bun run test
