# Build and publish help-desk-ui using npm and Gradle

name: Gradle Package

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: help-desk-ui
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
        node-version: 16
     - run: npm ci
     - run: npm run build --omit=dev
     - name: Get NPM Version
       id: package-version
       uses: martinbeentjes/npm-get-version-action@main
     - name: Create zip
       run: |
        cd dist/help-desk-ui
        zip -r help-desk-ui-${{steps.package-version.outputs.current-version}}-SNAPSHOT.zip .
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: 'gradle'
     - name: Publish to GitHub Packages with Gradle
       working-directory: help-desk-ui
       env:
         PUBLISH_VERSION: ${{ steps.package-version.outputs.current-version }}-SNAPSHOT
         USERNAME: ${{ github.actor }}
         TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: gradle publish -PpublishVersion="$PUBLISH_VERSION"
