package com.endeavorms.velocity.qto.report;

public class ReportHeaders {

    public static final String[] INVENTORY_HEADERS = {
            "Client Location ID",
            "Client Service ID",
            "Alternate ID",
            "Service Type (i90 Service)",
            "location Address 1",
            "Location Address 2",
            "Location City",
            "Location State/ Province",
            "Location Zip Code",
            "Location Country",
            "Service Inventory Activity Flag",
            "Sub Product Type",
            "Master Customer",
            "End Customer",
            "Client Project Manager",
            "i90 Project Manager",
            "Service Billed to",
            "Project",
            "Provider",
            "Service MRC",
            "Contract Term",
            "Contract Signed Date",
            "Contract End Date",
            "Ignore for Renewals Checkbox",
            "Product Speed",
            "Summary Bill",
            "Account # / BAN",
            "Commissions Supplier",
            "Commissions Account Number",
            "Sub Agent",
            "Secondary Agency",
            "Tertiary Agency",
            "Parent TSD",
            "Gross Profit",
            "Gross Profit MRC",
            "Uplift MRC",
            "Has Pending MACD",
            "Pending MACD Type",
            "Source",
            "Managed Service Flag",
            "MRC Change Last Year",
            "MRC Change All Time",
            "Has Pending Dispute (Open Disputes)",
            "MRC Dispute Amounts (Sum if Multiple)",
            "NRC Dispute Amounts (Sum if Multiple)",
            "Date Entered in Inventory",
            "Billing Address 1",
            "Billing Address 2",
            "Billing City",
            "Billing State",
            "Billing Zip / Postal Code",
            "Billing Country",
            "Billing Email"
    };


    public static final String[] WIP_HEADERS = {
            "Client Location ID",
            "Client Service ID",
            "Alternate ID",
            "Service Type (i90 Service)",
            "location Address 1",
            "Location Address 2",
            "Location City",
            "Location State/ Province",
            "Location Zip Code",
            "Location Country",
            "Service Status",
            "Service Sub-Status",
            "Sub Product Type",
            "Order Type",
            "Sub order Type",
            "Master Customer",
            "End Customer",
            "Provisioner",
            "Client Project Manager",
            "i90 Project Manager",
            "Service Billed to",
            "Project",
            "Provider",
            "Service MRC",
            "Service NRC",
            "Contract Term",
            "Contract Signed Date",
            "Contract End Date",
            "Ignore for Renewals Checkbox",
            "Product Speed",
            "Created Date",
            "Engineer Assigned Date",
            "Provider Order Submitted Date",
            "Network Provider FOC Date",
            "Data Provisioning Complete Date",
            "On Hold Date",
            "Complete Date",
            "Commissions Supplier",
            "Commissions Account Number",
            "Sub Agent",
            "Secondary Agency",
            "Tertiary Agency",
            "Parent TSD",
            "Gross Profit",
            "Gross Profit MRC",
            "Uplift MRC",
            "Billing Address 1",
            "Billing Address 2",
            "Billing City",
            "Billing State",
            "Billing Zip / Postal Code",
            "Billing Country",
            "Billing Email"
    };
}
