plugins {
    id 'maven-publish'
}

group = 'com.vertek.corporate'
version = '1.16.0-SNAPSHOT'

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri('https://maven.pkg.github.com/Vertek-Corporation/qto-ui')
            credentials {
                username = project.findProperty('gpr.user') ?: System.getenv('USERNAME')
                password = project.findProperty('gpr.key') ?: System.getenv('TOKEN')
            }
        }
    }
    publications {
        gpr(MavenPublication) {
            def zipVersion = project.findProperty('publishVersion') ?: version
            def zipFile = file("dist/qto-ui/qto-ui-${zipVersion}.zip")
            artifact(zipFile) {
                extension = 'zip'
            }
            groupId = 'com.vertek.corporate'
            artifactId = 'qto-ui'
            version = zipVersion
        }
    }
}
