#============================================================================
# Configure Main Scheduler Properties
#============================================================================

org.quartz.scheduler.instanceName = ${qto.org.quartz.scheduler.instanceName}

org.quartz.scheduler.instanceId = AUTO
org.quartz.scheduler.skipUpdateCheck = true
org.quartz.scheduler.dbFailureRetryInterval = 10000

#============================================================================
# Configure ThreadPool
#============================================================================

org.quartz.threadPool.threadCount = 5

#============================================================================
# Jobstore
#============================================================================

org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreCMT


#============================================================================
# Database backed JobStore
#============================================================================

org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.dataSource=myDS
org.quartz.jobStore.nonManagedTXDataSource=myDS
org.quartz.jobStore.txIsolationLevelReadCommitted=true
org.quartz.jobStore.isClustered=true
org.quartz.jobStore.clusterCheckinInterval=60000

#============================================================================
# Datasource(s)
#============================================================================

org.quartz.dataSource.myDS.jndiURL = java:jboss/datasources/qto


#===================================================
# Configure the Job Initialization Plugin
#===================================================

org.quartz.plugin.jobInitializer.class = org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin
org.quartz.plugin.jobInitializer.fileNames = quartz-jobs.xml
org.quartz.plugin.jobInitializer.failOnFileNotFound = true

# Set the scan interval to 0 to disable scanning because classloader issues when deployed in jboss prevent the file
# from being found and the resulting error was bloating the logs - 08/18/2012 - JDD
org.quartz.plugin.jobInitializer.scanInterval = 0
org.quartz.plugin.jobInitializer.wrapInUserTransaction = false

# cleanShutdown set to false so that jvm shut down won't be blocked by stuck job.  (NOCP-141)
org.quartz.plugin.shutdownhook.class = org.quartz.plugins.management.ShutdownHookPlugin
org.quartz.plugin.shutdownhook.cleanShutdown = false
