# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Publish

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo under $GITHUB_WORKSPACE
        uses: actions/checkout@v4
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      - name: print out file
        run: cat $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml
      - name: Build with Maven
        run: mvn clean install -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml
        env:
          GITHUB_USER_REF: mwelicka
          GITHUB_TOKEN_REF: ${{ secrets.RC_PACKAGES_READ_WRITE_TOKEN }}
      - name: Publish to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml
        env:
          GITHUB_USER_REF: mwelicka
          GITHUB_TOKEN_REF: ${{ secrets.RC_PACKAGES_READ_WRITE_TOKEN }}
