import { Address } from "./address.model";
import { Service } from "./service.model";

export class EthernetService extends Service {
  productType: string;
  portSpeed: string;
  eaSpeed: string;
  mtu: string;
  mux: string;
  vlanForEline: string;
  vlanTagging: string;
  vlanId: string;
  cableCategory: string;
  cableShielding: string;
  dataCenterName: string;
  accessType: string;
  interfaceConnector: string;
  accessHours: string;
  manned: string;
  loaRequired: string;
  handoffFiberMode: string;
  handoffConnectorType: string;
  clliCode: string;
  popClli: string;
  alternatePopClli: string;
  floor: string;
  npaNxx: string;
  cfa: string;
  zDataCenterName: string;
  zProviderCircuitId: string;
  zBuildingStatus: string;
  zAccessType: string;
  zInterfaceConnector: string;
  zAccessHours: string;
  zManned: string;
  zLoaRequired: string;
  zInsideWiringRequired: string;
  zHandoffMediaType: string;
  zHandoffFiberMode: string;
  zHandoffConnectorType: string;
  zClliCode: string;
  zPopClli: string;
  zAlternatePopClli: string;
  zFloor: string;
  zNpaNxx: string;
  zDmarc: string;
  zCfa: string;
  accessSpeed: string;
  zAddress1: string;
  zAddress2: string;
  zCity: string;
  zState: string;
  zPostalCode: string;
  zCountry: string;
}
