import { BaseSearchCriteria, DateSearchCriteriaField } from "./base-search-criteria.model";

export class ServiceCyberViewSearchCriteria extends BaseSearchCriteria {
  search: string;
  locationId: number[];
  locationIdComparison: any[];
  clientLocationId: number;
  parentCompanyName: string;
  parentCompanyClientId: string;
  companyName: string;
  endCustomerClientId: string;
  serviceType: string[];
  address: string;
  status: string;
  followUpDate = new DateSearchCriteriaField();
  provisioner: string[];
  i90ProjectManager: string[];
  provider: string;
  statusAge: number[];
  statusAgeComparison: any[];
  mrc: number[];
  mrcComparison: any[];
  nrc: number[];
  nrcComparison: any[];
  equipmentTypes: string;
  equipmentCount: number;
  equipmentCountRange: any[];
  customerRequestedInstall = new DateSearchCriteriaField();
  created = new DateSearchCriteriaField();
  techDataGatheringFormSent = new DateSearchCriteriaField();
  techDataGatheringMeetingScheduled = new DateSearchCriteriaField();
  techDataGatheringMeetingCompleted = new DateSearchCriteriaField();
  emailUsmAnywhereTemplateRequirementsSent = new DateSearchCriteriaField();
  inventoryAssignmentVerified = new DateSearchCriteriaField();
  newUsmAnywhereServerBuildStarted = new DateSearchCriteriaField();
  implementationQaCompleted = new DateSearchCriteriaField();
  verifyAssetsInSiemDb = new DateSearchCriteriaField();
  verifyLoggingDataSource = new DateSearchCriteriaField();
  scheduleVulnerabilityScans = new DateSearchCriteriaField();
  bulkAlarmTuningPhase1 = new DateSearchCriteriaField();
  siemEventFiltering = new DateSearchCriteriaField();
  filtersBuiltForReports = new DateSearchCriteriaField();
  defaultAlarmRuleAdditions = new DateSearchCriteriaField();
  customAlarmRuleAdditions = new DateSearchCriteriaField();
  forwardAlarmsToUsmCentral = new DateSearchCriteriaField();
  forwardAlarmsToD3SocLive = new DateSearchCriteriaField();
  hostListProvidedByClient = new DateSearchCriteriaField();
  halcyonPackageGivenToClient = new DateSearchCriteriaField();
  halcyonDeployedToHosts = new DateSearchCriteriaField();
  devopsNotifiedOfHalcyonAddition = new DateSearchCriteriaField();
  halcyonApiTokenAddedToD3 = new DateSearchCriteriaField();
  d3ConnectionVerified = new DateSearchCriteriaField();
  endLearningMode = new DateSearchCriteriaField();
  testEmailSentToClient = new DateSearchCriteriaField();
  deployConsultingTenant = new DateSearchCriteriaField();
  deployVulnerabilityScans = new DateSearchCriteriaField();
  providedCustomerWithReport = new DateSearchCriteriaField();
  discussFutureCyrismaManagement = new DateSearchCriteriaField();
  reviewExistingCaAndMfaPolicies = new DateSearchCriteriaField();
  signInPoliciesEnabled = new DateSearchCriteriaField();
  conditionalAccessPolicyVerification = new DateSearchCriteriaField();
  geographicRestrictionsEnabled = new DateSearchCriteriaField();
  deviceComplianceEnabled = new DateSearchCriteriaField();
  passwordResetEnabledForSelfService = new DateSearchCriteriaField();
  breakGlassAccountConfigured = new DateSearchCriteriaField();
  pimEnablement = new DateSearchCriteriaField();
  implementationVerified = new DateSearchCriteriaField();
}
