/**
 * Invoicing Page
 * Invoice list with search and navigation to invoice detail
 */

import { useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Search, X } from 'lucide-react';
import { format } from 'date-fns';

import { DataTable, type DataTableColumn } from '@/shared/components/DataTable';
import {
  useSearchInvoicesQuery,
  type Invoice,
} from '@/services/api/invoicesApi';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { AppPage, PageHeader, PageToolbar } from '@/components/layout/PageScaffold';

export default function InvoicingPage() {
  const navigate = useNavigate();
  const [offset, setOffset] = useState(0);
  const [pageSize, setPageSize] = useState(25);
  const [search, setSearch] = useState('');

  const { data, isLoading, error, refetch } = useSearchInvoicesQuery({ offset, limit: pageSize, search: search || undefined });

  const handlePageChange = useCallback((page: number) => {
    setOffset(page * pageSize);
  }, [pageSize]);

  const handlePageSizeChange = useCallback((size: number) => {
    setPageSize(size);
    setOffset(0);
  }, []);

  const handleSearch = useCallback(() => {
    setOffset(0);
    refetch();
  }, [refetch]);

  const formatCurrency = (value: number | null | undefined) =>
    value != null ? `$${Number(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '$0.00';

  const formatDate = (value: string | null | undefined) =>
    value ? format(new Date(value), 'MM/dd/yyyy') : '';

  const getStatusVariant = (status: string) => {
    switch (status?.toLowerCase()) {
      case 'finalized': return 'default' as const;
      case 'draft': return 'secondary' as const;
      case 'sent': return 'outline' as const;
      default: return 'secondary' as const;
    }
  };

  const columns: DataTableColumn<Invoice>[] = [
    { id: 'clientName', label: 'Client', sortable: true, width: 180 },
    {
      id: 'invoiceNumber',
      label: 'Invoice Number',
      sortable: true,
      width: 150,
      format: (value, row) => (
        <span
          className="text-primary cursor-pointer hover:underline font-medium"
          onClick={() => navigate(`/invoicing/${row.id}`)}
        >
          {value || `INV-${row.id}`}
        </span>
      ),
    },
    {
      id: 'invoiceStatus',
      label: 'Status',
      sortable: true,
      width: 110,
      format: (value) => (
        <Badge variant={getStatusVariant(value)}>
          {value || 'Unknown'}
        </Badge>
      ),
    },
    { id: 'totalCharges', label: 'Total Charges', sortable: true, width: 130, align: 'right', format: formatCurrency },
    { id: 'invoiceStart', label: 'Invoice Start', sortable: true, width: 120, format: formatDate },
    { id: 'invoiceEnd', label: 'Invoice End', sortable: true, width: 120, format: formatDate },
    { id: 'generatedBy', label: 'Generated By', sortable: true, width: 140 },
    { id: 'generatedDate', label: 'Generated Date', sortable: true, width: 130, format: formatDate },
  ];

  const invoiceStats = [
    {
      label: 'Invoices',
      value: (data?.total || 0).toLocaleString(),
      detail: search ? 'Search narrowed' : 'All invoice records',
      tone: 'brand' as const,
    },
    {
      label: 'Page size',
      value: pageSize.toString(),
      detail: `${Math.floor(offset / pageSize) + 1} active`,
      tone: 'warm' as const,
    },
  ];

  return (
    <AppPage>
      <PageHeader
        eyebrow="Billing visibility"
        title="Invoicing"
        description="Search finalized and in-flight invoices with the same table rhythm used across operations and finance views."
        stats={invoiceStats}
      />

      <PageToolbar>
        <Input
          placeholder="Search invoices..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
          className="h-11 max-w-sm rounded-xl border-slate-200 bg-white shadow-none"
        />
        <Button className="h-11 rounded-xl" onClick={handleSearch}>
          <Search className="mr-2 h-4 w-4" />
          Search
        </Button>
        <Button className="h-11 rounded-xl" variant="outline" onClick={() => { setSearch(''); setOffset(0); }}>
          <X className="mr-2 h-4 w-4" />
          Clear
        </Button>
        <span className="app-page-toolbar-note">Use Enter for fast query submission.</span>
      </PageToolbar>

      <DataTable
        columns={columns}
        data={data?.collection || []}
        loading={isLoading}
        error={error ? 'Failed to load invoices' : null}
        page={Math.floor(offset / pageSize)}
        pageSize={pageSize}
        totalElements={data?.total || 0}
        onPageChange={handlePageChange}
        onPageSizeChange={handlePageSizeChange}
        onRefresh={refetch}
        title={`${data?.total || 0} Invoices`}
        exportFileName="invoices"
        exportEnabled
      />
    </AppPage>
  );
}
