# Database connection
url=jdbc:mysql://localhost:3306/qto?useSSL=false&serverTimezone=UTC
username=qto_user
password=qto_pass
driver=com.mysql.cj.jdbc.Driver

# Liquibase changelog (filesystem path is easiest for Maven)
changeLogFile=database/changelog-master.xml
searchPath=src/main/resources

classpath=C:/ProgramData/chocolatey/lib/mysql-connector-java/tools/mysql-connector-java-8.0.15/mysql-connector-java-8.0.15.jar
driver=com.mysql.cj.jdbc.Driver


# Contexts (IMPORTANT)
contexts=common,dev

# Optional (depends on how scripts are written)
# defaultSchemaName=qto