<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>qto</artifactId>
        <groupId>com.vertek.corporate</groupId>
        <version>1.18.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>qto-war</artifactId>
    <packaging>war</packaging>

    <dependencies>
        <dependency>
            <groupId>com.vertek.corporate</groupId>
            <artifactId>qto-rest-api</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-maven-plugin</artifactId>
                <version>4.0.0.Final</version>
                <configuration>
                    <name>qto.war</name>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.3.2</version>
                <configuration>
                    <webResources>
                        <!--copy resource file location-->
                        <resource>
                            <directory>${project.build.directory}/classes</directory>
                        </resource>
                    </webResources>
                    <!--location for add file-->
                    <webappDirectory>${project.build.directory}/${project.build.finalName}</webappDirectory>
                </configuration>
            </plugin>

        </plugins>
    </build>

</project>
