export const INVOICE_COLUMNS = [
  { name: 'Client', propertyName: 'clientName', type: 'text', hidden: false, filterable: false },
  { name: 'Invoice Number', propertyName: 'invoiceNumber', type: 'text', hidden: false, filterable: false },
  { name: 'Status', propertyName: 'invoiceStatus', type: 'text', hidden: false, filterable: false },
  { name: 'Total Charges', propertyName: 'totalCharges', type: 'currency', hidden: false, filterable: false },
  { name: 'Invoice Start', propertyName: 'invoiceStart', type: 'date', hidden: false, filterable: false },
  { name: 'Invoice End', propertyName: 'invoiceEnd', type: 'date', hidden: false, filterable: false },
  { name: 'Generated By', propertyName: 'generatedBy', type: 'text', hidden: false, filterable: false },
  { name: 'Genrated Date', propertyName: 'generatedDate', type: 'date', hidden: false, filterable: false }
]
