package com.endeavorms.velocity.qto.fileimport.ethernet;

import com.endeavorms.velocity.qto.fileimport.AbstractInventoryServiceImportColumns;

import java.util.ArrayList;

/**
 * @author rcasey
 * @since 1/18/2024
 */
final class EthernetImportColumns extends AbstractInventoryServiceImportColumns {
    static final String ADDRESS_1 = "Address 1 (A)";
    static final String ADDRESS_2 = "Address 2 (A)";
    static final String CITY = "City (A)";
    static final String STATE_PROVINCE_REGION = "State/Province/Region (A)";
    static final String ZIP_POSTAL_CODE = "Zip/Postal code (A)";
    static final String COUNTRY = "Country (A)";
    static final String TIME_ZONE = "Time Zone (A)";
    static final String Z_ADDRESS_1 = "Address 1 (Z)";
    static final String Z_ADDRESS_2 = "Address 2 (Z)";
    static final String Z_CITY = "City (Z)";
    static final String Z_STATE_PROVINCE_REGION = "State/Province/Region (Z)";
    static final String Z_ZIP_POSTAL_CODE = "Zip/Postal code (Z)";
    static final String Z_COUNTRY = "Country (Z)";
    static final String CLIENT_LOCATION_INFO = "Client Location Info";
    static final String CLIENT_LOCATION_TYPE = "Client Location Type";
    static final String QUOTE_SOLUTION_ID = "Quote Solution ID";
    static final String PROJECT_NAME = "Project Name";
    static final String SERVICE_BILLED_TO = "Service Billed To";
    static final String PROVIDER = "Provider";
    static final String UNDERLYING_PROVIDER = "Underlying Provider";
    static final String SUB_PRODUCT_TYPE = "Sub Product Type";
    static final String PO_NUMBER = "PO Number";
    static final String MANAGED_SERVICE = "Managed Service";
    static final String PRODUCTION_IMPACTING = "Production Impacting";
    static final String PRODUCT_TYPE = "Product Type";
    static final String CONTRACT_TERM = "Contract Term";
    static final String CONTRACT_SIGNED_DATE = "Contract Signed Date";
    static final String CONTRACT_END_DATE = "Contract End Date";
    static final String PROVIDER_ORDER_NUMBER = "Provider Order #";
    static final String BILL_CYCLE = "Bill Cycle";
    static final String ACCOUNT_NUMBER_BAN = "Account Number / BAN";
    static final String SUMMARY_BILL = "Summary Bill";
    static final String PORT_SPEED = "Port Speed";
    static final String ACCESS_SPEED = "Access Speed";
    static final String EA_SPEED = "EA Speed";
    static final String CIRCUIT_INSTALLED_DATE = "Circuit Installed Date";
    static final String INTERFACE_CONNECTOR = "Interface Connector";
    static final String MTU = "MTU";
    static final String TRUNK_GROUP = "Trunk Group";
    static final String MUX = "MUX";
    static final String CE_VLAN_FOR_E_LINE = "CE-VLAN for E-Line";
    static final String VLAN_TAGGING = "VLAN Tagging";
    static final String VLAN_ID = "VLAN ID";
    static final String CABLE_CATEGORY = "Cable Category";
    static final String CABLE_SHIELDING = "Cable Shielding";
    static final String IP_FORMAT = "IP Format";
    static final String WAN_IPS = "WAN IP's";
    static final String WAN_GATEWAY = "WAN Gateway";
    static final String WAN_SUBNET = "WAN Subnet";
    static final String LAN_IPS = "LAN IP's";
    static final String LAN_GATEWAY = "LAN Gateway";
    static final String LAN_SUBNET = "LAN Subnet";
    static final String TSP_CODE = "TSP Code";
    static final String TSP_CODE_EXPIRATION_DATE = "TSP Code Expiration Date";
    static final String NOTES_TO_IMPORT = "Notes to Import";
    static final String A_END_MRC = "A End MRC (A)";
    static final String A_END_NRC = "A End NRC (A)";
    static final String ANNUAL_RECURRING_COST = "Annual Recurring Cost";
    static final String A_PROVIDER_CIRCUIT_ID = "Provider Circuit ID (A)";
    static final String A_ACCESS_TYPE = "Access Type (A)";
    static final String A_INTERFACE_CONNECTOR = "Interface Connector (A)";
    static final String A_ACCESS_HOURS = "Access Hours (A)";
    static final String A_MANNED = "Manned (A)";
    static final String A_LOA_REQUIRED = "LOA Required (A)";
    static final String A_HANDOFF_MEDIA_TYPE = "Handoff Media Type (A)";
    static final String A_HANDOFF_FIBER_MODE = "Handoff Fiber Mode (A)";
    static final String A_HANDOFF_CONNECTOR_TYPE = "Handoff Connector Type (A)";
    static final String A_CLLI_CODE = "CLLI Code (A)";
    static final String A_POP_CLLI = "POP CLLI (A)";
    static final String A_ALTERNATE_POP_CLLI = "Alternate POP CLLI (A)";
    static final String A_FLOOR = "Floor (A)";
    static final String A_NPA_NXX = "NPA/NXX (A)";
    static final String A_DMARC = "DMARC (A)";
    static final String A_CFA = "CFA (A)";
    static final String Z_END_MRC = "Z End MRC (Z)";
    static final String Z_END_NRC = "Z End NRC (Z)";
    static final String Z_PROVIDER_CIRCUIT_ID = "Provider Circuit ID (Z)";
    static final String Z_ACCESS_TYPE = "Access Type (Z)";
    static final String Z_INTERFACE_CONNECTOR = "Interface Connector (Z)";
    static final String Z_ACCESS_HOURS = "Access Hours (Z)";
    static final String Z_MANNED = "Manned (Z)";
    static final String Z_LOA_REQUIRED = "LOA Required (Z)";
    static final String Z_HANDOFF_MEDIA_TYPE = "Handoff Media Type (Z)";
    static final String Z_HANDOFF_FIBER_MODE = "Handoff Fiber Mode (Z)";
    static final String Z_HANDOFF_CONNECTOR_TYPE = "Handoff Connector Type (Z)";
    static final String Z_CLLI_CODE = "CLLI Code (Z)";
    static final String Z_POP_CLLI = "POP CLLI (Z)";
    static final String Z_ALTERNATE_POP_CLLI = "Alternate POP CLLI (Z)";
    static final String Z_FLOOR = "Floor (Z)";
    static final String Z_NPA_NXX = "NPA/NXX (Z)";
    static final String Z_DMARC = "DMARC (Z)";
    static final String Z_CFA = "CFA (Z)";

    private static final ArrayList<String> COL_LIST = new ArrayList<>();

    static {
        COL_LIST.add(MASTER_CUSTOMER);
        COL_LIST.add(END_CUSTOMER);
        COL_LIST.add(I90_PROJECT_MANAGER);
        COL_LIST.add(CLIENT_LOCATION_ID);
        COL_LIST.add(CLIENT_SERVICE_ID);
        COL_LIST.add(ADDRESS_1);
        COL_LIST.add(ADDRESS_2);
        COL_LIST.add(CITY);
        COL_LIST.add(STATE_PROVINCE_REGION);
        COL_LIST.add(ZIP_POSTAL_CODE);
        COL_LIST.add(COUNTRY);
        COL_LIST.add(TIME_ZONE);
        COL_LIST.add(LOCATION_DESCRIPTION);
        COL_LIST.add(Z_ADDRESS_1);
        COL_LIST.add(Z_ADDRESS_2);
        COL_LIST.add(Z_CITY);
        COL_LIST.add(Z_STATE_PROVINCE_REGION);
        COL_LIST.add(Z_ZIP_POSTAL_CODE);
        COL_LIST.add(Z_COUNTRY);
        COL_LIST.add(SERVICE_DESCRIPTION);
        COL_LIST.add(LCON_NAME);
        COL_LIST.add(LCON_EMAIL);
        COL_LIST.add(LCON_PHONE);
        COL_LIST.add(CLIENT_LOCATION_INFO);
        COL_LIST.add(CLIENT_LOCATION_TYPE);
        COL_LIST.add(QUOTE_SOLUTION_ID);
        COL_LIST.add(PROJECT_NAME);
        COL_LIST.add(SERVICE_BILLED_TO);
        COL_LIST.add(PROVIDER);
        COL_LIST.add(UNDERLYING_PROVIDER);
        COL_LIST.add(SUB_PRODUCT_TYPE);
        COL_LIST.add(PO_NUMBER);
        COL_LIST.add(MANAGED_SERVICE);
        COL_LIST.add(PRODUCTION_IMPACTING);
        COL_LIST.add(PRODUCT_TYPE);
        COL_LIST.add(CONTRACT_TERM);
        COL_LIST.add(CONTRACT_SIGNED_DATE);
        COL_LIST.add(CONTRACT_END_DATE);
        COL_LIST.add(CONTRACT_INFO);
        COL_LIST.add(DATE_ENTERED_IN_INVENTORY);
        COL_LIST.add(PROVIDER_ORDER_NUMBER);
        COL_LIST.add(BILL_CYCLE);
        COL_LIST.add(ACCOUNT_NUMBER_BAN);
        COL_LIST.add(SUMMARY_BILL);
        COL_LIST.add(PORT_SPEED);
        COL_LIST.add(ACCESS_SPEED);
        COL_LIST.add(EA_SPEED);
        COL_LIST.add(CIRCUIT_INSTALLED_DATE);
        COL_LIST.add(INTERFACE_CONNECTOR);
        COL_LIST.add(MTU);
        COL_LIST.add(TRUNK_GROUP);
        COL_LIST.add(MUX);
        COL_LIST.add(CE_VLAN_FOR_E_LINE);
        COL_LIST.add(VLAN_TAGGING);
        COL_LIST.add(VLAN_ID);
        COL_LIST.add(CABLE_CATEGORY);
        COL_LIST.add(CABLE_SHIELDING);
        COL_LIST.add(IP_FORMAT);
        COL_LIST.add(WAN_IPS);
        COL_LIST.add(WAN_GATEWAY);
        COL_LIST.add(WAN_SUBNET);
        COL_LIST.add(LAN_IPS);
        COL_LIST.add(LAN_GATEWAY);
        COL_LIST.add(LAN_SUBNET);
        COL_LIST.add(TSP_CODE);
        COL_LIST.add(TSP_CODE_EXPIRATION_DATE);
        COL_LIST.add(NOTES_TO_IMPORT);
        COL_LIST.add(ANNUAL_RECURRING_COST);
        COL_LIST.add(ORIGINAL_MRC);
        COL_LIST.add(A_END_MRC);
        COL_LIST.add(A_END_NRC);
        COL_LIST.add(A_PROVIDER_CIRCUIT_ID);
        COL_LIST.add(A_ACCESS_TYPE);
        COL_LIST.add(A_INTERFACE_CONNECTOR);
        COL_LIST.add(A_ACCESS_HOURS);
        COL_LIST.add(A_MANNED);
        COL_LIST.add(A_LOA_REQUIRED);
        COL_LIST.add(A_HANDOFF_MEDIA_TYPE);
        COL_LIST.add(A_HANDOFF_FIBER_MODE);
        COL_LIST.add(A_HANDOFF_CONNECTOR_TYPE);
        COL_LIST.add(A_CLLI_CODE);
        COL_LIST.add(A_POP_CLLI);
        COL_LIST.add(A_ALTERNATE_POP_CLLI);
        COL_LIST.add(A_FLOOR);
        COL_LIST.add(A_NPA_NXX);
        COL_LIST.add(A_DMARC);
        COL_LIST.add(A_CFA);
        COL_LIST.add(Z_END_MRC);
        COL_LIST.add(Z_END_NRC);
        COL_LIST.add(Z_PROVIDER_CIRCUIT_ID);
        COL_LIST.add(Z_ACCESS_TYPE);
        COL_LIST.add(Z_INTERFACE_CONNECTOR);
        COL_LIST.add(Z_ACCESS_HOURS);
        COL_LIST.add(Z_MANNED);
        COL_LIST.add(Z_LOA_REQUIRED);
        COL_LIST.add(Z_HANDOFF_MEDIA_TYPE);
        COL_LIST.add(Z_HANDOFF_FIBER_MODE);
        COL_LIST.add(Z_HANDOFF_CONNECTOR_TYPE);
        COL_LIST.add(Z_CLLI_CODE);
        COL_LIST.add(Z_POP_CLLI);
        COL_LIST.add(Z_ALTERNATE_POP_CLLI);
        COL_LIST.add(Z_FLOOR);
        COL_LIST.add(Z_NPA_NXX);
        COL_LIST.add(Z_DMARC);
        COL_LIST.add(Z_CFA);
        COL_LIST.add(BILLING_ADDRESS_1);
        COL_LIST.add(BILLING_ADDRESS_2);
        COL_LIST.add(BILLING_CITY);
        COL_LIST.add(BILLING_STATE_PROVINCE_REGION);
        COL_LIST.add(BILLING_ZIP_POSTAL_CODE);
        COL_LIST.add(BILLING_COUNTRY);
        COL_LIST.add(BILLING_EMAIL);
    }

    private EthernetImportColumns() { }

    public static ArrayList<String> getExpectedColumns() {
        return COL_LIST;
    }

}
