package com.vertek.corporate.qto.fileimport.order;

import java.util.ArrayList;

/**
 * @author rcasey
 * @since 2/19/2024
 */
final class OrderImportColumns {

    static final String MASTER_CUSTOMER = "Master Customer";
    static final String END_CUSTOMER = "End Customer";
    static final String CLIENT_ORDER_ID = "Client Order ID";
    static final String CLIENT_LOCATION_ID = "Client Location ID";
    static final String ADDRESS_1 = "Address 1";
    static final String ADDRESS_2 = "Address 2";
    static final String CITY = "City";
    static final String STATE_PROVINCE_REGION = "State/Province/Region";
    static final String ZIP_POSTAL_CODE = "Zip/Postal code";
    static final String COUNTRY = "Country";
    static final String LCON_NAME = "LCON Name";
    static final String LCON_EMAIL = "LCON Email";
    static final String LCON_PHONE = "LCON Phone";
    static final String LOCATION_INFO = "Location Info";
    static final String LOCATION_TYPE = "Location Type";
//    static final String LEVEL_OF_EFFORT = "Level of Effort";
    static final String SERVICE = "Service";
    static final String CLIENT_SERVICE_ID = "Client Service ID";
    static final String DESCRIPTION = "Description";
    static final String QUOTE_ID = "Quote ID";
    static final String PROJECT_NAME = "Project Name";
    static final String PROVIDER = "Provider";
    static final String SERVICE_BILLED_TO = "Service Billed to";
    static final String SUB_PRODUCT_TYPE = "Sub Product Type";
    static final String SERVICE_INFO = "Service Info";
    static final String SERVICE_TYPE = "Service Type";
    static final String CONTRACT_TERM = "Contract Term";
    static final String CONTRACT_SIGNED_DATE = "Contract Signed Date";
    static final String PO_NUMBER = "PO Number";
    static final String MRC = "MRC";
    static final String NRC = "NRC";
    static final String ANNUAL_NRC = "Annual NRC";
    static final String AUTO_RENEWAL = "Auto Renewal";
    static final String CO_TERMINUS = "Co-Terminus";
    static final String NOTICE_PERIOD_FOR_RENEWAL = "Notice Period for Renewal/Cancel";
    static final String CONTRACT_INFO = "Contract Info";
    static final String CUSTOMER_REQUESTED_INSTALL_DATE = "Customer Requested Install Date";
    static final String UPLOAD_SPEED = "Upload Speed";
    static final String DOWNLOAD_SPEED = "Download Speed";
    static final String MEDIA_TYPE = "Media type";
    static final String DMARC = "DMARC";
    static final String FIELD_SERVICES_PROVIDER = "Field Services Provider";
    static final String ADDITIONAL_IP_BLOCK = "Additional IP Block";
    static final String LINKED_BUNDLED = "Linked or Bundled";
    static final String PARENT_CLIENT_SERVICE_ID = "Parent Client Service ID";
    static final String BILLING_ADDRESS_1 = "Billing Address 1";
    static final String BILLING_ADDRESS_2 = "Billing Address 2";
    static final String BILLING_CITY = "Billing City";
    static final String BILLING_STATE = "Billing State";
    static final String BILLING_ZIP = "Billing Zip";
    static final String BILLING_COUNTRY = "Billing Country";
    static final String BILLING_EMAIL = "Billing Email";
    static final String TECHNICAL_NAME = "Technical Name";
    static final String TECHNICAL_EMAIL = "Technical Email";
    static final String TECHNICAL_PHONE = "Technical Phone";
    static final String SALES_NAME = "Sales Name";
    static final String SALES_EMAIL = "Sales Email";
    static final String SALES_PHONE = "Sales Phone";
    static final String AUTHORIZATION_NAME = "Authorization Name";
    static final String AUTHORIZATION_EMAIL = "Authorization Email";
    static final String AUTHORIZATION_PHONE = "Authorization Phone";
    static final String COMMISSIONABLE_MRC = "Commissionable MRC";
    static final String COMMISSIONABLE_NRC = "Commissionable NRC";
    static final String COMMISSIONABLE_ARC = "Commissionable ARC";
    static final String SUB_AGENT = "Sub Agent";
    static final String SUB_AGENT_PERCENT = "Sub Agent %";
    static final String SUBMITTED_IN_ADV_TO_PROVIDER = "Submitted in Advance to Provider";
    static final String PARENT_TSD = "Parent TSD";
    static final String SUBMITTED_IN_ADV_TO_TSD = "Submitted in Advance to TSD";
    static final String REFERRAL_NAME_COMPANY = "Referral Name /Company";
    static final String COMPANY_REFERRAL_PERCENT = "Company Referral %";
    static final String COMMISSION_PAYMENT_TYPE = "Commission Payment Type";
    static final String EXPECTED_COMMISSION = "Expected Commission";
    static final String CIE_TEAMED_DEAL_INFO = "CIE/Teamed Deal Info";
    static final String COMMISSION_REDUCTION_PERCENT = "Commission Reduction Percent";
    static final String COMMISSIONS_ICB = "Commissions ICB";
    static final String INTERNAL_COMMISSIONS_COMMENTS = "Internal Commissions Comments";
    static final String SFA_OPPORTUNITY_NUM = "SFA Opportunity #";
    static final String NET_PROVIDER_POINTS = "Net Provider Points/Rate/Percent";
    static final String PROMOTIONS = "Promotions";
    static final String SPIFF_AMOUNT = "SPIFF Amount";
    static final String ENGINEER_RESOURCE = "Engineer Resource";
    static final String ENGINEER_RESOURCE_ALLOCATION = "Engineer Resource Allocation";
    static final String LUMEN_CIE_REP = "Lumen CIE Rep";
    static final String LUMEN_REGION = "Lumen Region";
    static final String IN_REGION_NEED_TAX_ID = "In Region- Need Tax ID";
    static final String IN_OUT_REGION_NEED_SALES_ID = "In & Out of Region- Need Sales ID";
    static final String LUMEN_AG = "Lumen AG";
    static final String ORDER_NUMBER = "Order #";
    static final String BTN = "BTN";
    private static final ArrayList<String> COL_LIST = new ArrayList<>();

    static {
        COL_LIST.add(MASTER_CUSTOMER);
        COL_LIST.add(END_CUSTOMER);
        COL_LIST.add(CLIENT_ORDER_ID);
        COL_LIST.add(CLIENT_LOCATION_ID);
        COL_LIST.add(ADDRESS_1);
        COL_LIST.add(ADDRESS_2);
        COL_LIST.add(CITY);
        COL_LIST.add(STATE_PROVINCE_REGION);
        COL_LIST.add(ZIP_POSTAL_CODE);
        COL_LIST.add(COUNTRY);
        COL_LIST.add(LCON_NAME);
        COL_LIST.add(LCON_EMAIL);
        COL_LIST.add(LCON_PHONE);
        COL_LIST.add(LOCATION_INFO);
        COL_LIST.add(LOCATION_TYPE);
//        COL_LIST.add(LEVEL_OF_EFFORT);
        COL_LIST.add(SERVICE);
        COL_LIST.add(CLIENT_SERVICE_ID);
        COL_LIST.add(DESCRIPTION);
        COL_LIST.add(QUOTE_ID);
        COL_LIST.add(PROJECT_NAME);
        COL_LIST.add(PROVIDER);
        COL_LIST.add(SERVICE_BILLED_TO);
        COL_LIST.add(SUB_PRODUCT_TYPE);
        COL_LIST.add(SERVICE_INFO);
        COL_LIST.add(SERVICE_TYPE);
        COL_LIST.add(CONTRACT_TERM);
        COL_LIST.add(CONTRACT_SIGNED_DATE);
        COL_LIST.add(PO_NUMBER);
        COL_LIST.add(MRC);
        COL_LIST.add(NRC);
        COL_LIST.add(ANNUAL_NRC);
        COL_LIST.add(AUTO_RENEWAL);
        COL_LIST.add(CO_TERMINUS);
        COL_LIST.add(NOTICE_PERIOD_FOR_RENEWAL);
        COL_LIST.add(CONTRACT_INFO);
        COL_LIST.add(CUSTOMER_REQUESTED_INSTALL_DATE);
        COL_LIST.add(UPLOAD_SPEED);
        COL_LIST.add(DOWNLOAD_SPEED);
        COL_LIST.add(MEDIA_TYPE);
        COL_LIST.add(DMARC);
        COL_LIST.add(FIELD_SERVICES_PROVIDER);
        COL_LIST.add(ADDITIONAL_IP_BLOCK);
        COL_LIST.add(LINKED_BUNDLED);
        COL_LIST.add(PARENT_CLIENT_SERVICE_ID);
        COL_LIST.add(BILLING_ADDRESS_1);
        COL_LIST.add(BILLING_ADDRESS_2);
        COL_LIST.add(BILLING_CITY);
        COL_LIST.add(BILLING_STATE);
        COL_LIST.add(BILLING_ZIP);
        COL_LIST.add(BILLING_COUNTRY);
        COL_LIST.add(BILLING_EMAIL);
        COL_LIST.add(TECHNICAL_NAME);
        COL_LIST.add(TECHNICAL_EMAIL);
        COL_LIST.add(TECHNICAL_PHONE);
        COL_LIST.add(SALES_NAME);
        COL_LIST.add(SALES_EMAIL);
        COL_LIST.add(SALES_PHONE);
        COL_LIST.add(AUTHORIZATION_NAME);
        COL_LIST.add(AUTHORIZATION_EMAIL);
        COL_LIST.add(AUTHORIZATION_PHONE);
        COL_LIST.add(COMMISSIONABLE_MRC);
        COL_LIST.add(COMMISSIONABLE_NRC);
        COL_LIST.add(COMMISSIONABLE_ARC);
        COL_LIST.add(SUB_AGENT);
        COL_LIST.add(SUB_AGENT_PERCENT);
        COL_LIST.add(SUBMITTED_IN_ADV_TO_PROVIDER);
        COL_LIST.add(PARENT_TSD);
        COL_LIST.add(SUBMITTED_IN_ADV_TO_TSD);
        COL_LIST.add(REFERRAL_NAME_COMPANY);
        COL_LIST.add(COMPANY_REFERRAL_PERCENT);
        COL_LIST.add(COMMISSION_PAYMENT_TYPE);
        COL_LIST.add(EXPECTED_COMMISSION);
        COL_LIST.add(CIE_TEAMED_DEAL_INFO);
        COL_LIST.add(COMMISSION_REDUCTION_PERCENT);
        COL_LIST.add(COMMISSIONS_ICB);
        COL_LIST.add(INTERNAL_COMMISSIONS_COMMENTS);
        COL_LIST.add(SFA_OPPORTUNITY_NUM);
        COL_LIST.add(NET_PROVIDER_POINTS);
        COL_LIST.add(PROMOTIONS);
        COL_LIST.add(SPIFF_AMOUNT);
        COL_LIST.add(ENGINEER_RESOURCE);
        COL_LIST.add(ENGINEER_RESOURCE_ALLOCATION);
        COL_LIST.add(LUMEN_CIE_REP);
        COL_LIST.add(LUMEN_REGION);
        COL_LIST.add(IN_REGION_NEED_TAX_ID);
        COL_LIST.add(IN_OUT_REGION_NEED_SALES_ID);
        COL_LIST.add(LUMEN_AG);
        COL_LIST.add(ORDER_NUMBER);
        COL_LIST.add(BTN);
    }

    private OrderImportColumns() { }

    static ArrayList<String> getExpectedColumns() {
        return COL_LIST;
    }
}
