spring:
  main:
    allow-circular-references: true
  application:
    name: qto
  datasource:
    url: jdbc:postgresql://localhost:5433/qto-main
    username: qto_user
    password: changeme
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:database/postgresql-baseline.xml
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.artemis.ArtemisAutoConfiguration

server:
  port: 8085
  servlet:
    context-path: /qto
  error:
    include-message: always
    include-stacktrace: on_param
