spring:
  main:
    allow-circular-references: true
  application:
    name: qto
  datasource:
    url: jdbc:postgresql://localhost:5433/qto-main
    username: qto_user
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:database/postgresql-baseline.xml
    enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.artemis.ArtemisAutoConfiguration
      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration

server:
  port: 8081
