spring:
  main:
    allow-circular-references: true
  application:
    name: qto
  datasource:
    url: jdbc:mysql://localhost:3307/qto?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: qto_user
    password: changeme
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
      - org.springframework.boot.autoconfigure.jms.artemis.ArtemisAutoConfiguration

server:
  port: 8080
